### ISSUE TITLE
`tier pull | tier push -` reports error about adding feature to existing plan

### ISSUE THREAD

**Issue by isaacs** [tierrun/tier#177] opened 2022-11-22 23:33 UTC
### What is the issue?

Pull the model with `tier pull`.  Immediately try to push that exact same json.  It reports an error about adding a feature to an existing plan.

### Steps to reproduce

```
tier pull | tier push -
```

Result:

```
$ tier pull | tier push -
failed	plan:free@6	feature:convert	-	[plan already exists]
failed	plan:pro@7	feature:convert	-	[plan already exists]
failed	plan:foo@2	feature:bar	-	[plan already exists]
failed	plan:free@1	feature:convert	-	[plan already exists]
failed	plan:pro@1	feature:convert	-	[plan already exists]
failed	plan:pro@1	feature:hello	-	[plan already exists]
failed	plan:foo@3	feature:bar	-	[plan already exists]
failed	plan:free@3	feature:convert	-	[plan already exists]
failed	plan:foo@1	feature:bar	-	[plan already exists]
failed	plan:free@4	feature:convert	-	[plan already exists]
failed	plan:pro@6	feature:convert	-	[plan already exists]
failed	plan:windowstesting@0	feature:hello	-	[plan already exists]
failed	plan:foo@0	feature:bar	-	[plan already exists]
failed	plan:pro@2	feature:convert	-	[plan already exists]
failed	plan:foo@4	feature:bar	-	[plan already exists]
failed	plan:pro@5	feature:convert	-	[plan already exists]
tier: illegal attempt to push features to existing plan(s); aborting.
```

### Tier version

$ tier version 0.5.2-dev20221122   tier commit: 83ea6c8e8c0cd9031ddf5320d57fb48cc32da59c-dirty   go version: go1.19beta1

**Comment by isaacs** [comment] 2022-11-22 23:35
It reports an error and fails even if there was a plan added, and no other changes made, but the new plan does get created:

```
$ tier push pricing.json
failed	plan:free@4	feature:convert	-	[plan already exists]
failed	plan:free@1	feature:convert	-	[plan already exists]
failed	plan:pro@6	feature:convert	-	[plan already exists]
failed	plan:foo@2	feature:bar	-	[plan already exists]
failed	plan:foo@0	feature:bar	-	[plan already exists]
failed	plan:free@6	feature:convert	-	[plan already exists]
failed	plan:windowstesting@0	feature:hello	-	[plan already exists]
failed	plan:foo@3	feature:bar	-	[plan already exists]
failed	plan:pro@2	feature:convert	-	[plan already exists]
failed	plan:foo@4	feature:bar	-	[plan already exists]
failed	plan:pro@1	feature:convert	-	[plan already exists]
failed	plan:pro@1	feature:hello	-	[plan already exists]
failed	plan:free@3	feature:convert	-	[plan already exists]
failed	plan:pro@7	feature:convert	-	[plan already exists]
failed	plan:pro@5	feature:convert	-	[plan already exists]
failed	plan:foo@1	feature:bar	-	[plan already exists]
ok	plan:thisisfine@0	feature:coffee	https://dashboard.stripe.com/acct_15MpCwKajPHS2Vke/prices/price_1M75zKKajPHS2VketGMnodzU	[created]
tier: illegal attempt to push features to existing plan(s); aborting.
```

**Comment by bmizerany** [comment] 2022-11-22 23:54
This works as intended. If you intended to only push a single plan, please trim down your pricing.json to only that plan; otherwise tier will assume you intend to update plans, which is illegal.

**Comment by bmizerany** [comment] 2022-11-22 23:59
If you're running `tier pull | tier push -` in an attempt to migrate from pre-`v0.5.2` to `v0.5.2` then the first push will report "feature already exists" and subsequent pushes will say "plan already exists". This is because pre-v0.5.2 there are no sentinel products pushed for use in determining if plan has been pushed, so they are created during this _first_ push. On the second push, tier encounters the sentinel product (put there by the recent but previous push) before attempting to push features, which results in `[plan already exists]`.

It is worth noting:  It is not _normal_ to pull and then to push a model to and from the same account. It's usually done under special circumstances such as data migrations.

**Comment by bmizerany** [comment] 2022-11-23 20:47
Closing. Please open a feature request if you feel strongly that this behavior should change.

**Closed as completed by bmizerany** 2022-11-23 20:47 UTC
Labels: bug
